name: example
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  fields_generator:
    path: ../

dev_dependencies:
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
