name: fields_generator
version: 0.1.3
description: Fields name generator for Dart
homepage: https://github.com/masreplay/fields_generator

environment:
  sdk: ^3.8.0

dependencies:
  build: '>=3.1.0 <5.0.0'
  source_gen: '>=3.1.0 <5.0.0'
  analyzer: ^9.0.0

  json_annotation: ^4.11.0
  change_case: ^2.2.0
  source_helper: ^1.3.10

dev_dependencies:
  build_runner: ^2.11.1
  grinder: ^0.9.5
